### ISSUE TITLE
API for doing things?

### ISSUE THREAD

**Issue by daUnknownCoder** [mrquantumcodes/bufferchad.nvim#8]
I would like an API like harpoon has -> `lua require("harpoon").mark()` something like that...
so that i can more lazy load it in the `keys = {}` of lazy.nvim

how to mark buffer? like i ain't familiar with `mset`

**Comment by mrquantumcodes** [comment]
Done, please check out the readme.

To clarify, `mset` was the keymap for adding a buffer to marks. Previously you couldn't change this mapping, now you can.

Also, there is a new API function to do the same thing so you can lazy load now.
